apiVersion: v1
kind: Pod
metadata:
  name: fastapi-motor-skeleton
spec:
  containers:
    - name: fastapi-motor-skeleton
      image: fastapi-motor-skeleton
      env:
        - name: LOG_LEVEL
          value: DEBUG
        - name: MONGODB_URL
          value: mongodb://username:password@mongodb:27017/app
        - name: MONGODB_DBNAME
          value: app
