on:
  push:
  pull_request:

jobs:
  ci:
    services:
      mongodb:
        image: bitnami/mongodb:4.4.8
        ports:
          - 27017:27017
        env:
          MONGODB_USERNAME: username
          MONGODB_PASSWORD: password
          MONGODB_DATABASE: app
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codes
        uses: actions/checkout@v2
      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: Cache .venv
        id: cache
        uses: actions/cache@v2
        with:
          key: python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
          path: .venv
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ${HOME}/.poetry/bin/poetry install
      - name: Test
        run: |
          ./test.sh
        env:
          LOG_LEVEL: DEBUG
          MONGODB_URL: mongodb://username:password@localhost:27017/app
          MONGODB_DBNAME: app
